= User Guide: @coswitch
:page-permalink: /:path/index.html
:page-layout: page_tools_opam
:page-pkg: tools_opam
:page-doc: ug
:page-otags: [opam,tools]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: June 16, 2022
:page-toc: True
:toc:

// * link:opam-overview[OPAM Overview]
// * link:coswitches[OPAM Switches & OBazl Coswitches]: seamless OPAM integration

// * link:opam-configuration[OPAM configuration]
// * link:local-switches[OPAM Local Switches]
// * link:opam-interrogation[Interrogating OPAM configurations]

The OBazl rules for OCaml can be used with both system and local OPAM switches:

* "system" switches are installed in the OPAM "root", which is usually `$HOME/.opam`.
* local switches are installed in the project directory, in a subdirectory usually named `_opam`.  See link:https://opam.ocaml.org/blog/opam-local-switches/[OPAM Local Switches] for more information.

Support for OPAM integration is provided by rule `ocaml_import`, which
makes precompiled artifacts available to Bazel build actions. To
import an (installed) OPAM package, all that is needed is

* a `MODULE.bazel` file in the package root directory, that defines
  the package as a Bazel module and lists its dependencies;
* a `BUILD.bazel` file containing an `ocaml_import` target that imports the files of the package;
* if the package contains subpackages, a `BUILD.bazel` file for each; and
* a record in a Bazel module registry to make the package accessible via the Bazel module dependency management system.

The `@coswitch` module contains a `@coswitch//new` target that
automatically generates these files and installs them locally.

NOTE: Nothing is written to the OPAM switch. All generated files and directories are written to a dedicated directory in `$XDG_DATA_HOME` or in the `.config/` subdirectory of the project (for local OPAM switches). Symlinks are used to expose files in the switch.

== Installation

In `MODULE.bazel`:

    bazel_dep(name = "coswitch", version = "1.0.0")

This module is not yet registered with the
link:https://bcr.bazel.build[Bazel Central Registry]; until it is, put
the following in `.bazelrc`:

----
common --enable_bzlmod
common --registry=https://raw.githubusercontent.com/obazl/registry/main/
common --registry=https://bcr.bazel.build
----


== Usage

The `@coswitch` Bazel module provides the following `bazel run` targets:

* `@coswitch//new` - generates an OBazl coswitch corresponding to the current switch, or a switch passed via `-s` or `--switch`.
* `@coswitch//show` - prints information about the active coswitch to stdout.

The generated coswitch contains one Bazel module for each package in
the switch. The build targets follow this schema: for packages,
`@<pkg>//lib/<pkg>`; for segmented subpackages,
`@<pkg>//lib/<seg1>/<seg2>`. For example:

* `yojson` => `@yojson//lib/yojson`
* `mtime.clock.os` => `@mtime//lib/clock/os`

== The coswitch registry

`bazel run @coswitch//new` generates a Bazel module registry for the
packages in the switch. For system switches it is located at

    $XDG_DATA_HOME/obazl/registry/<switch>

Usually `$XDG_DATA_HOME` is `$HOME/.local`, so for example the registry record for the `yojson` package in switch `5.1.0` would be:

    $HOME/.local/obazl/registry/5.1.0/modules/yojson

For local switches, the registry is located at
`<root>/.config/obazl/registry`; note that the switch name is omitted
from the path. So with a local opam switch, regardless of compiler
version, the registry record for yojson package would be at

    <root>/.config/obazl/registry/modules/yojson

=== The `--registry` directive

Once the registry has been generated, you must direct Bazel to use it for module lookups.  The OBazl convention is to write the registry directive to `<root>/.config/coswitch_registry.bazelrc`, and to add `try-import .config/coswitch_registry.bazelrc` to the root `.bazelrc` file.  The `@coswitch//new` command will overwrite `.config/coswitch_registry.bazelrc` with the path to the generated registry.  An example is:

    common --registry=file:///<home>/<uid>/.local/share/obazl/registry/5.0.0


