= OCaml: Toolchains
:page-permalink: /:path/toolchains
:page-layout: page_rules_ocaml
:page-pkg: ocaml
:page-doc: ocaml
:page-tags: [ocaml,toolchain]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: May 16, 2022
:toc-title:
:toc: true


Standard OCaml distributions contain no fewer than four toolchains.  ...

IMPORTANT: The current OBazl toolsuite uses one OPAM-based Bazel
toolchain that contains all the tools in the selected OPAM switch
(i.e. OCaml distribution). Build mode (bytecode or native) is
controlled by a configurable default rule passed on the command line;
see X for details. The profiling compilers are not supported. The next
version will contain one Bazel toolchain for each OCaml toolchain.

== Compilers

[cols="1,1,1,1"]
|===
| | bytecode binaries | native binaries | remarks

.2+.^|emit bytecode:
|ocamlc.byte
|ocamlc.opt
| std compilers

|ocamlcp.byte
|ocamlcp.opt
| profiling compilers

.2+.^|emit native code:
|ocamlopt.byte
|ocamlopt.opt
| std compilers

|ocamloptp.byte
|ocamloptp.opt
| profiling compilers

|===

NOTE: These are all utility commands. The actually compilers are
implemented as libraries; these commands are actually drivers, like
the `gcc` command of the GNU toolchain. They run the compilers but may
also run other tools.

The `\*.opt` versions are native code binaries; the `*.byte` versions
are bytecode binaries, which must be executed with
link:https://v2.ocaml.org/manual/runtime.html[ocamlrun,window="_blank"].

The profiling complers instrument the source code, adding code to
record how many times functions are called, branches of conditionals
are taken, etc.  See also link:https://v2.ocaml.org/manual/instrumented-runtime.html[Runtime tracing with the instrumented runtime,window="_blank"].

By default, names without an extension are symlinked to the optimized (native) binaries:

* ocamlc -> ocamlc.opt
* ocamlcp -> ocamlcp.opt
* ocamlopt -> ocamlopt.opt
* ocamloptp -> ocamloptp.opt

By default, the OBazl rules use `ocamlopt.opt`: the native-code compiler binary that emits native code.

== Linkage

Native-mode compilers depend on a C toolchain; they may emit and
compile assembly code, and use the linker.

Bytecode-mode compilers handle everything by themselves; they do not
need a linker or other C tools (unless the source code uses interop to
use libraries produced by another language system (C, Rust, etc.) ?)


== Other tools

The OCaml toolchain includes a variety of tools, most of which come in
`\*.byte` and `*.opt` variants. Some but not all come with a `man` page.

* link:https://v2.ocaml.org/manual/toplevel.html[ocaml,window="_blank"] - a toplevel system (i.e. REPL) for OCaml
* `ocamlcmt` - reads a `.cmt` file and prints related information
* link:https://v2.ocaml.org/manual/debugger.html[ocamldebug,window="_blank"] - the OCaml source-level replay debugger
* link:https://v2.ocaml.org/manual/depend.html[ocamldep,window="_blank"] - dependency generator: scans source files and emits dependency information
* link:https://v2.ocaml.org/manual/ocamldoc.html[ocamldoc,window="_blank"] -  documentation generator
* link:https://v2.ocaml.org/manual/lexyacc.html#s%3Aocamllex-overview[ocamllex,window="_blank"] - lexer generator
* `ocamlmklib` - generate libraries with mixed C / Caml code
* `ocamlmktop` - builds OCaml toplevels that contain user code preloaded at start-up
* `ocamlobjinfo` - prints information from `.cmo/.cmx/.cmi` files
* link:https://v2.ocaml.org/manual/profil.html[ocamlprof,window="_blank"] - OCaml profiler
* link:https://v2.ocaml.org/manual/runtime.html[ocamlrun,window="_blank"] - executes bytecode files produced by the linking phase of the ocamlc command.
* `ocamlrund` - debug version of `ocamlrun`
* `ocamlruni` - instrumented variant of `ocamlrun` (see link:https://v2.ocaml.org/manual/instrumented-runtime.html[Runtime tracing with the instrumented runtime,window="_blank"])
* link:https://v2.ocaml.org/manual/lexyacc.html#s%3Aocamlyacc-overview[ocamlyacc,window="_blank"] - parser generator


== Third-party Tools

=== ocamlfind and the findlib library

link:http://projects.camlcity.org/projects/findlib.html[findlib,window="_blank"]
is an OCaml package manager library. It has largely been supplanted by OPAM,
but the metadata language it defines is used by OPAM.


link:https://github.com/ocaml/ocamlfind[ocamlfind,window="_blank"] is a commonly used command-line interface to the `findlib` library.

=== OPAM

link:https://opam.ocaml.org/[OPAM] is the standard OCaml package manager.

=== Dune

link:https://github.com/ocaml/dune[Dune] is the most commonly used
build system for OCaml. Many if not most OPAM packages use Dune.

OBazl is an alternative to Dune.

=== Other

* link:https://github.com/Octachron/codept[codept,window="_blank"] - alternative dependency solver
* link:https://github.com/ocaml-community/cppo[cppo,window="_blank"] - preprocessor, modeled on the C preprocessor


