theme: jekyll-theme-hacker
title: "OBazl Documentation"
name: "OBazl docs"
description: Documentation for <a href="https://github.com/obazl/rules_ocaml">obazl_rules_ocaml</a> and obazl_rules_opam
markdown: kramdown
