theme: jekyll-theme-hacker
title: "OBazl documentation"
name: "OBazl docs"
description: Documentation for [obazl_rules_ocaml](https://github.com/obazl/rules_ocaml) and obazl_rules_opam
markdown: kramdown
