---
layout: home
---

= OBazl: rules_ocaml

This site documents the first Beta version of OBazl. The OBazl rules
are deliberately low-level, in keeping with the goal of giving the
developer complete control (i.e. no magic). Obazl build rules
correspond more-or-less directly to the build commands they construct.
The down side of sugar-free rules is a degree of inconvenience. For
example, OBazl does not analyze implicit dependencies, so it is the
responsibility of the developer to discover and list them. It does not
support file globbing, so each source file must have a build rule.
Most such inconveniences can and will be addressed over time by
tooling built on the foundation of the primitive rules.

* rules_ocaml:
  ** link:rules_ocaml/ug/index[User Guide]
  ** link:rules_ocaml/refman/index[Reference Manual]

* tools_opam:
** link:tools_opam/ug/index[User Guide]
** link:tools_opam/refman/index[Reference Manual]



== Demos

* https://github.com/obazl/dev_obazl[dev_obazl]

// * link:deployments/mina


== Github

* https://github.com/obazl/rules_ocaml[rules_ocaml]
* https://github.com/obazl/tools_opam[tools_opam]
// * https://github.com/obazl/tools_obazl[tools_obazl]


== Support
* Discord: [OBazl](https://discord.gg/PHSAW5DUva)
* Twitter: [@obazldev](https://twitter.com/obazldev)


=== Acknowledgements

Support for the development of OBazl was provided by a Mina Genesis
Token Grant and the generous assistance of the [Mina](https://minaprotocol.com/) team.
